package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"data-hub/graph/generated"
	model "data-hub/model/graph"
	"data-hub/model/upstream"
	"encoding/json"
	"fmt"
	"time"

	"go.uber.org/zap"
)

// Disbursements is the resolver for the disbursements field.
func (r *loanDataResolver) Disbursements(ctx context.Context, obj *model.LoanData) ([]*model.Disbursement, error) {
	cacheKey := fmt.Sprintf("gqdg:%s:disbursement", obj.ApplicationID)

	// 1. Check cache
	cached, err := r.Cache.Get(ctx, cacheKey)
	if err != nil {
		r.Logger.Error("cache get error", zap.String("key", cacheKey), zap.Error(err))
	}
	if cached != "" {
		r.Logger.Debug("cache hit", zap.String("key", cacheKey))
		var items []*model.Disbursement
		if jsonErr := json.Unmarshal([]byte(cached), &items); jsonErr == nil {
			return items, nil
		}
	}
	r.Logger.Debug("cache miss", zap.String("key", cacheKey))

	// 2. Call admin API
	apiResp, err := r.AdminClient.FetchDisbursement(ctx, obj.ApplicationID)
	if err != nil {
		r.Logger.Warn("disbursement fetch failed, returning nil",
			zap.String("app_id", obj.ApplicationID),
			zap.Error(err),
		)
		return nil, nil
	}

	r.Logger.Info("disbursement parsed",
		zap.String("app_id", obj.ApplicationID),
		zap.Bool("success", apiResp.Success),
		zap.Int("count", len(apiResp.Data)),
	)

	if len(apiResp.Data) == 0 {
		return nil, nil
	}

	// 3. Map upstream records → GraphQL model list
	items := make([]*model.Disbursement, 0, len(apiResp.Data))
	for _, record := range apiResp.Data {
		items = append(items, &model.Disbursement{
			Utr:              strPtr(record.Utr),
			DisbursalDate:    strPtr(record.DisbursalDate),
			DisbursementType: record.DisbursementType, // already *string, can be null
			TranchDetails:    mapTranchDetails(record.TranchDetails),
		})
	}

	// 4. Store in cache
	if bytes, marshalErr := json.Marshal(items); marshalErr == nil {
		_ = r.Cache.Set(ctx, cacheKey, string(bytes), r.Config.CacheTTL.Disbursement)
	}

	return items, nil
}

// ApplicationDetails is the resolver for the applicationDetails field.
func (r *loanDataResolver) ApplicationDetails(ctx context.Context, obj *model.LoanData) (*model.ApplicationDetails, error) {
	cacheKey := fmt.Sprintf("gqdg:%s:application_summary", obj.ApplicationID)

	// 1. Check cache
	cached, err := r.Cache.Get(ctx, cacheKey)
	if err != nil {
		r.Logger.Error("cache get error", zap.String("key", cacheKey), zap.Error(err))
	}
	if cached != "" {
		r.Logger.Debug("cache hit", zap.String("key", cacheKey))
		var item model.ApplicationDetails
		if jsonErr := json.Unmarshal([]byte(cached), &item); jsonErr == nil {
			return &item, nil
		}
	}
	r.Logger.Debug("cache miss", zap.String("key", cacheKey))

	// 2. Call summary and tracker independently — failure of one must not blank the other.
	item := &model.ApplicationDetails{}
	gotAny := false

	if apiResp, sErr := r.AdminClient.FetchApplicationSummary(ctx, obj.ApplicationID); sErr != nil {
		r.Logger.Warn("application summary fetch failed, leaving stage/product/tags null",
			zap.String("app_id", obj.ApplicationID),
			zap.Error(sErr),
		)
	} else {
		rec := apiResp.Data
		tags := make([]*string, 0, len(rec.ProductTags))
		for _, t := range rec.ProductTags {
			v := t
			tags = append(tags, &v)
		}
		item.CurrentStage = strPtr(rec.CurrentStage)
		item.ProductName = strPtr(rec.ProductName)
		item.ProductTags = tags
		gotAny = true
	}

	if trackerResp, tErr := r.AdminClient.FetchTracker(ctx, obj.ApplicationID); tErr != nil {
		r.Logger.Warn("tracker fetch failed, leaving currentApplicationTracker null",
			zap.String("app_id", obj.ApplicationID),
			zap.Error(tErr),
		)
	} else if len(trackerResp.Data.Results) > 0 {
		item.CurrentApplicationTracker = strPtr(trackerResp.Data.Results[0].Slug)
		gotAny = true
	}

	// If both upstreams returned nothing useful, treat as no data.
	if !gotAny {
		return nil, nil
	}

	// 4. Store in cache
	if bytes, marshalErr := json.Marshal(item); marshalErr == nil {
		_ = r.Cache.Set(ctx, cacheKey, string(bytes), r.Config.CacheTTL.Application)
	}

	return item, nil
}

// Kyc is the resolver for the kyc field.
func (r *loanDataResolver) Kyc(ctx context.Context, obj *model.LoanData) ([]*model.Kyc, error) {
	cacheKey := fmt.Sprintf("gqdg:%s:kyc", obj.ApplicationID)

	// 1. Check cache
	cached, err := r.Cache.Get(ctx, cacheKey)
	if err != nil {
		r.Logger.Error("cache get error", zap.String("key", cacheKey), zap.Error(err))
	}
	if cached != "" {
		r.Logger.Debug("cache hit", zap.String("key", cacheKey))
		var items []*model.Kyc
		if jsonErr := json.Unmarshal([]byte(cached), &items); jsonErr == nil {
			return items, nil
		}
	}
	r.Logger.Debug("cache miss", zap.String("key", cacheKey))

	// 2. Call KYC service
	apiResp, err := r.KycClient.FetchKycStatus(ctx, obj.ApplicationID)
	if err != nil {
		r.Logger.Warn("kyc fetch failed, returning nil",
			zap.String("app_id", obj.ApplicationID),
			zap.Error(err),
		)
		return nil, nil
	}

	// 3. Map non-null KYC records → GraphQL model list
	d := apiResp.Data
	items := make([]*model.Kyc, 0, 4)
	addKyc := func(kycType string, rec *upstream.KycRecord) {
		if rec == nil {
			return
		}
		t, s := kycType, rec.Status
		items = append(items, &model.Kyc{KycType: &t, KycStatus: &s})
	}
	addKyc("okyc", d.OkycData)
	addKyc("ckyc", d.CkycData)
	addKyc("pkyc", d.PkycData)
	addKyc("vkyc", d.VkycData)

	// 4. Store in cache
	if bytes, marshalErr := json.Marshal(items); marshalErr == nil {
		_ = r.Cache.Set(ctx, cacheKey, string(bytes), r.Config.CacheTTL.Kyc)
	}

	return items, nil
}

// Refunds is the resolver for the refunds field.
func (r *loanDataResolver) Refunds(ctx context.Context, obj *model.LoanData) ([]*model.Refund, error) {
	cacheKey := fmt.Sprintf("gqdg:%s:refunds", obj.ApplicationID)

	// 1. Check cache
	cached, err := r.Cache.Get(ctx, cacheKey)
	if err != nil {
		r.Logger.Error("cache get error", zap.String("key", cacheKey), zap.Error(err))
	}
	if cached != "" {
		r.Logger.Debug("cache hit", zap.String("key", cacheKey))
		var items []*model.Refund
		if jsonErr := json.Unmarshal([]byte(cached), &items); jsonErr == nil {
			return items, nil
		}
	}
	r.Logger.Debug("cache miss", zap.String("key", cacheKey))

	// 2. Call admin API
	apiResp, err := r.AdminClient.FetchRefunds(ctx, obj.ApplicationID)
	if err != nil {
		r.Logger.Warn("refunds fetch failed, returning nil",
			zap.String("app_id", obj.ApplicationID),
			zap.Error(err),
		)
		return nil, nil
	}

	if len(apiResp.Data.Results) == 0 {
		return nil, nil
	}

	// 3. Map upstream records → GraphQL model list
	items := make([]*model.Refund, 0, len(apiResp.Data.Results))
	for _, rec := range apiResp.Data.Results {
		amount := rec.RefundAmount
		items = append(items, &model.Refund{
			RefundAmount: &amount,
			Status:       strPtr(rec.Status),
			InitiatedOn:  strPtr(rec.InitiatedOn),
			SettledOn:    strPtr(rec.SettledOn),
		})
	}

	// 4. Store in cache
	if bytes, marshalErr := json.Marshal(items); marshalErr == nil {
		_ = r.Cache.Set(ctx, cacheKey, string(bytes), r.Config.CacheTTL.Refund)
	}

	return items, nil
}

// Payments is the resolver for the payments field.
func (r *loanDataResolver) Payments(ctx context.Context, obj *model.LoanData) ([]*model.Payment, error) {
	cacheKey := fmt.Sprintf("gqdg:%s:payments", obj.ApplicationID)

	// 1. Check cache
	cached, err := r.Cache.Get(ctx, cacheKey)
	if err != nil {
		r.Logger.Error("cache get error", zap.String("key", cacheKey), zap.Error(err))
	}
	if cached != "" {
		r.Logger.Debug("cache hit", zap.String("key", cacheKey))
		var items []*model.Payment
		if jsonErr := json.Unmarshal([]byte(cached), &items); jsonErr == nil {
			return items, nil
		}
	}
	r.Logger.Debug("cache miss", zap.String("key", cacheKey))

	// 2. Call admin API
	apiResp, err := r.AdminClient.FetchPayments(ctx, obj.ApplicationID)
	if err != nil {
		r.Logger.Warn("payments fetch failed, returning nil",
			zap.String("app_id", obj.ApplicationID),
			zap.Error(err),
		)
		return nil, nil
	}

	if len(apiResp.Data.Results) == 0 {
		return nil, nil
	}

	// 3. Map upstream records → GraphQL model list
	// status derived from is_success: 1 → SUCCESS, 0 → FAILED
	items := make([]*model.Payment, 0, len(apiResp.Data.Results))
	for _, rec := range apiResp.Data.Results {
		status := "FAILED"
		if rec.IsSuccess == 1 {
			status = "SUCCESS"
		}
		amount := rec.TransactionData.TransactionAmount
		items = append(items, &model.Payment{
			TransactionID:   strPtr(rec.TransactionData.TransactionID),
			Amount:          &amount,
			TransactionDate: strPtr(rec.TransactionData.Date),
			Status:          &status,
			Mode:            strPtr(rec.Source),
		})
	}

	// 4. Store in cache
	if bytes, marshalErr := json.Marshal(items); marshalErr == nil {
		_ = r.Cache.Set(ctx, cacheKey, string(bytes), r.Config.CacheTTL.Payments)
	}

	return items, nil
}

// RepaymentAndEmi is the resolver for the repaymentAndEmi field.
func (r *loanDataResolver) RepaymentAndEmi(ctx context.Context, obj *model.LoanData) (*model.RepaymentAndEmi, error) {
	cacheKey := fmt.Sprintf("gqdg:%s:repayment", obj.ApplicationID)

	// 1. Check cache
	cached, err := r.Cache.Get(ctx, cacheKey)
	if err != nil {
		r.Logger.Error("cache get error", zap.String("key", cacheKey), zap.Error(err))
	}
	if cached != "" {
		r.Logger.Debug("cache hit", zap.String("key", cacheKey))
		var item model.RepaymentAndEmi
		if jsonErr := json.Unmarshal([]byte(cached), &item); jsonErr == nil {
			return &item, nil
		}
	}
	r.Logger.Debug("cache miss", zap.String("key", cacheKey))

	// 2. Call repayment service
	apiResp, err := r.RepaymentClient.FetchSchedule(ctx, obj.ApplicationID)
	if err != nil {
		r.Logger.Warn("repayment schedule fetch failed, returning nil",
			zap.String("app_id", obj.ApplicationID),
			zap.Error(err),
		)
		return nil, nil
	}

	entries := apiResp.Data.RepaymentData.RepaymentSchedule.CombinedData
	if len(entries) == 0 {
		return nil, nil
	}

	// 3. Compute counters/overdue/dpd from combined_data
	result := computeRepaymentAndEmi(entries, time.Now().UTC())

	// nextEmiDate, nextEmiAmount, and totalAmountPaid come from upstream's
	// precomputed payment_summary — same source the customer-facing UI uses.
	ps := apiResp.Data.PaymentSummary
	if ps.UpcomingDueDate != "" {
		d := ps.UpcomingDueDate
		result.NextEmiDate = &d
	}
	if ps.UpcomingEmiAmount > 0 {
		a := ps.UpcomingEmiAmount
		result.NextEmiAmount = &a
	}
	if ps.TotalAmountPaid > 0 {
		p := ps.TotalAmountPaid
		result.TotalAmountPaid = &p
	}

	// 4. Store in cache
	if bytes, marshalErr := json.Marshal(result); marshalErr == nil {
		_ = r.Cache.Set(ctx, cacheKey, string(bytes), r.Config.CacheTTL.Repayment)
	}

	return result, nil
}

// LoanData is the resolver for the loanData query.
// It just stores the applicationId — no API calls here.
// Child resolvers are only called when those fields are requested.
func (r *queryResolver) LoanData(ctx context.Context, applicationID string) (*model.LoanData, error) {
	return &model.LoanData{ApplicationID: applicationID}, nil
}

// LoanData returns generated.LoanDataResolver implementation.
func (r *Resolver) LoanData() generated.LoanDataResolver { return &loanDataResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type loanDataResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
