namespace:
  name: gq-app
  create: false

replicaCount: 2

nameOverride: ""
fullnameOverride: "data-hub"

image:
  repository: 527877698776.dkr.ecr.ap-south-1.amazonaws.com/data-hub
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

serviceAccount:
  create: false
  name: "gq-app-sa"
  annotations: {}

rbac:
  create: false
  rules: []

podAnnotations:
  security.kubernetes.io/seccompProfile: "runtime/default"

podLabels: {}

containerPort: 8080

probes:
  path: /health

  liveness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  startup:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 12
    timeoutSeconds: 5

nodeSelector: {}

tolerations: []

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {}
  labels: {}

ingress:
  enabled: true
  className: alb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: prod-ingress-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-south-1:527877698776:certificate/5339f5f9-6517-4c98-93ab-ea51ffa05034"

  hosts:
    - host: data-hub-prod.grayquest.com
      paths:
        - path: /
          pathType: Prefix

configmap:
  enabled: false

secret:
  enabled: false

externalSecrets:
  enabled: true
  refreshInterval: "1m"
  secretStoreName: "aws-secretsmanager"
  secretStoreKind: "ClusterSecretStore"
  awsSecretName: "gq-data-hub-secret"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

pdb:
  enabled: false
  minAvailable: 1

env: []

envFromSecrets: []
```
